a lot of benchmark stuff

diff --git a/benchmarks/Makefile b/benchmarks/Makefile
--- a/benchmarks/Makefile
+++ b/benchmarks/Makefile
@@ -1,11 +1,21 @@
-.PHONY: clean all
+.PHONY: clean all all-json all-fuse all-futil result
 
 JSON_URL:=https://raw.githubusercontent.com/nlohmann/json/develop/single_include/nlohmann/json.hpp
-SOURCES:=$(wildcard *.data)
+SOURCES:=$(wildcard *.json)
 
-all: $(patsubst %.data,%.run,$(SOURCES))
+all: $(patsubst %.json,%.run,$(SOURCES))
 
-%.cpp: %.fuse.pre
+status:
+	@echo "`ls -l *.run | wc -l`/`ls -l *.fuse | wc -l` successfully ran"
+	@echo "`cat *.run | grep success | wc -l`/`ls -l *.run | wc -l` passed"
+
+all-fuse: $(patsubst %.json,%.run-fuse,$(SOURCES))
+
+all-futil: $(patsubst %.json,%.run-futil,$(SOURCES))
+
+all-json: $(patsubst %.data,%.json,$(wildcard *.data))
+
+%.cpp: %.fuse.pre %.json
 	fuse run $< -o $@ -x "-Iprint_headers/"
 	@if [ ! -f _headers/json.hpp ]; then wget $(JSON_URL) --directory-prefix _headers; fi
 
@@ -16,17 +26,22 @@ all: $(patsubst %.data,%.run,$(SOURCES))
 	fuse -b futil $< -o $@
 
 %.run-fuse: %.cpp
-	./$(addsuffix .cpp.o,$*) $(addsuffix .data,$*) >> $@
+	./$(addsuffix .cpp.o,$*) $(addsuffix .json,$*) > $@
 
 %.run-futil: %.futil
-	racket $< -c $(addsuffix .data,$*) >> $@
+	racket $< -c $(addsuffix .json,$*) > $@
+
+%.json:
+	racket $(addsuffix .data,$*)
 
 %.run: %.run-fuse %.run-futil
-	@if diff -y $?; then \
-		echo -e "[\e[32mTEST\e[0m] $* passed!"; \
+	@if ./diff.py $?; then \
+		echo -e "[\e[32mBENCHMARK\e[0m] $* passed!"; \
+		echo success > $(addsuffix .run,$*); \
 	else \
-		echo -e "[\e[31mTEST\e[0m] $* failed!"; \
+		echo -e "[\e[31mBENCHMARK\e[0m] $* failed!"; \
+		echo failure > $(addsuffix .run,$*); \
 	fi
 
 clean:
-	rm -rf *.cpp *.o _headers *.out *.run-fuse *.run-futil *.run-futil-hand *.futil *.pre
+	rm -rf *.cpp *.o _headers *.out *.run-fuse *.run-futil *.run *.futil *.pre
